### ISSUE TITLE
Documentation: How to run different shaders than the default waveforms (command line options, keyboard shortcuts, help overlay)?

### ISSUE THREAD

**Issue by almereyda** [bradleybauer/music_visualizer#7]
After following the build instructions, a `shaders` directory is prepopulated with presets to use.

Unfortunately no command line options are documented, that would explain how to load a `shader.json` from another preset root. The only known key to work is `q`.

As a user of the binary, I would like to learn about the keyboard shortcuts in an informative overlay (after pressing F1), in order to quickly access the applications functions.

Additionally I would like to be able to run the binary with regular `--version` and `--help` flags, to identify its expected ways of working.

Further I would expect the program to accept parameters where to read its configuration from.

Are these desires that are within a scope to be fulfill-able?

**Comment by almereyda** [comment]
In an ideal scenario, I would be able to follow a tutorial to reproduce the screenshots.

**Comment by bradleybauer** [comment]
Those are great ideas but I am not working on this code anymore. Feel free to fork the repo and do whatever you want with it.

There are no command line options at the moment and q/Esc is the only keyboard shortcut. You are right, it would be great to have an overlay.

The program will load whichever shader.json is in it's current working directory. The way I change shaders is to just replace the files (json, frag, geom) in the current working directory with a copy of the files from preset folder you want. If the program is running then it will detect that the files have changed and will reload everything. So you should be able to change which shader you are rendering on the fly.
